### ISSUE TITLE
Docker | Gazebo gzclient GUI not displaying on OS X El Capitan

### ISSUE THREAD

**Issue by ceobillionaire** [erlerobot/gym-gazebo#10]
On _OS X El Capitan_ (version 10.11.6), when running:

```
export GAZEBO_MASTER_IP=$(sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' "id of running container")
export GAZEBO_MASTER_URI=$GAZEBO_MASTER_IP:11345
gzclient
```

Nothing happens (I have Gazebo version 7.3.1 installed locally).

Launching `gazebo` alone is working.

**Comment by vmayoral** [comment]
+1, reproduced it and got the same result. No response for `gzclient`.

**Comment by Nestor94Gonzalez** [comment]
This feature has been tested just in Ubuntu14.

**Comment by rdaries29** [comment]
Hello,

I have encountered the same error on OS X Sierra (version 10.12.3). When I launch the _circuit2_turtlebot_lidar_qlearn.py_ file, it does perform episodes but I am unable to visualise the environment. Launching gazebo alone is working. The command gzclient is unresponsive for a second.

![screen shot 2017-08-18 at 4 38 03 pm](https://user-images.githubusercontent.com/8170120/29469188-11e7e592-843f-11e7-904c-ad811662b91f.png)

**Comment by AliBaheri** [comment]
Same problem here on the same system!

**Comment by vmayoral** [comment]
Docker container is not being maintained anymore. Refer to https://github.com/erlerobot/gym-gazebo/issues/44 for more details.
