### ISSUE TITLE
Unable to register with master node 

### ISSUE THREAD

**Issue by tegg89** [erlerobot/gym-gazebo#104]
Hi, I followed all steps from `Readme` and successfully installed `gym_gazebo` and `turtlebot` setup.
At first, I have opencv problem which is unable to import. However, after including `PYTHONPATH` into `bashrc`, I can import both `cv2` and `gym_gazebo'. 
Then, I have trouble running `circuit2_turtlebot_lidar_qlearn.py`. 
```
(torch) tegg@tegg-MS-7984:~/gym-gazebo/examples/turtlebot$ python3 circuit2_turtlebot_lidar_qlearn.py 
[2018-02-26 17:17:26,272] Making new env: GazeboCircuit2TurtlebotLidar-v0
Traceback (most recent call last):
  File "/opt/ros/kinetic/bin/roscore", line 69, in <module>
    import roslaunch
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 51, in <module>
    from . import param_dump as roslaunch_param_dump
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/param_dump.py", line 40, in <module>
    import roslaunch.config
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/config.py", line 45, in <module>
    import rospkg.distro
  File "/home/tegg/anaconda3/envs/torch/lib/python3.5/site-packages/rospkg/distro.py", line 44, in <module>
    import yaml
  File "/home/tegg/anaconda3/envs/torch/lib/python3.5/site-packages/yaml/__init__.py", line 284
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid syntax
Roscore launched!
Unable to register with master node [http://localhost:11311]: master may not be running yet. Will keep trying.
```
I use Ubuntu 16.04 LTS and Anaconda environment with Python 3. 
How can I figure this out?

Thanks in advance.

**Comment by JaxDraxler** [comment]
Hi !!
I've had similar issues with opencv and ROS. What i did was use python2 and so i was able to immediately import cv2 without having to do any extra step. I don't know if this helps !!

**Comment by pulver22** [comment]
Hi,

I am actually working on an implementation of PPO using CNN for navigating the turtlebot. What I get is that after a while, I get the error regarding the communication with the master node (which is running). Did you experience something similar?

**Comment by mohsinlakhani** [comment]
@pulver22 I am facing the same issue after letting my Softlearning algo running with Gazebo for about an hour or so. I believe in my case it might be due to ROS not closing sockets and eventually running into an exception. Looking into it. Let me know if you solved the issue.

**Comment by DafangWang** [comment]
![image](https://user-images.githubusercontent.com/22852599/51099318-f921eb00-180a-11e9-9029-dd06b861b7d4.png)
Try to change the ROS_MASTER_URI to equal to the ROS_MASTER_URI of roscore

**Comment by DafangWang** [comment]
Yes, right. Thank you very much for your response !

**Comment by nzlz** [comment]
@mohsinlakhani if you are still facing problems please open an **Advice request** issue to facilitate issue-tracking. If you found the solution please feel free to post it below, even if this issue remains closed.

**Comment by mohsinlakhani** [comment]
I just resolved the issue. In the turtlebot example `rospy.wait_for_msg` was continuously creating socket connections to the point that the PC could not create any more. Changing it to the traditional Subscriber with a callback solved the issue for me.
