### ISSUE TITLE
Navigation and Objects Avoidance

### ISSUE THREAD

**Issue by hlinh0411hd** [erlerobot/gym-gazebo#115]
Hi, I read some papers about Robot Navigation and one of problems is robot navigate to an objects or a target. I remember we had a problem in gym-gazebo but it seem that we lost that file.
Now I want to build that problem. Do you have ideas to determine a target in maps? One of my idea is using position however it's hard to reach exactly the target. Can we use camera in someways?
And other question is how to define the reward of that problem.
Thank you.

**Comment by nzlz** [comment]
Hi @hlinh0411hd , answer coming late, but your proposal seems very feasible. Please open an **Advice request** issue to facilitate issue-tracking if you are still interested.
