### ISSUE TITLE
not  able to see copter in Gazebo simulation 

### ISSUE THREAD

**Issue by mymultiverse** [erlerobot/gym-gazebo#117]
I am loading and running the copter environment and example respectively with following commands, which run almost fine (with error message FCU: PreArm: RC not calibrated with UDP port log info.).

```sudo docker run -it erlerobotics/gym-gazebo
sudo pip install pandas
cd /usr/local/gym/gym-gazebo/gym_gazebo/envs/installation
xvfb-run -s "-screen 0 1400x900x24" bash
bash erlecopter_setup.bash
source catkin_ws/devel/setup.bash
cd /usr/local/gym/gym-gazebo/examples/scripts_erlecopter
python erlecopter_hover_qlearn.py
``` 

In the new terminal, I launch 

    gzclient

After launching gazebo I am getting this.
![selection_072](https://user-images.githubusercontent.com/14858165/37645250-a3136ab4-2c69-11e8-90a8-a0d655322e13.png)

**Comment by JaxDraxler** [comment]
@mymultiverse Hello !! Have you found a solution for this ?

**Comment by mymultiverse** [comment]
@JaxDraxler not yet.

**Comment by nzlz** [comment]
If any of you is still interested/facing this issue please open a **Bug report** to facilitate issue-tracking and we will try to help you.
