### ISSUE TITLE
Possibility of a boilerplate

### ISSUE THREAD

**Issue by TheCamusean** [erlerobot/gym-gazebo#128]
Hi,

I have been dealing with the package and I think it would be interesting adding a boilerplate for an easy development of new enviroments accesible to gym.

I have started to do something.

**Comment by vmayoral** [comment]
Partially related to https://github.com/erlerobot/gym-gazebo/issues/96.

Any contributions on this regard will be very welcome.

**Comment by mkhansen-intel** [comment]
@TheCamusean - what do you mean by boilerplate in this case? I'm looking to make some improvements as well, so I'd like to know so I don't make conflicting changes.

**Comment by TheCamusean** [comment]
Hii,

I was thinking in a kind of template with some instructions, in order to make easy to develop new enviroments even if you are a newby either with Gym or Python. 

I started developing something in a fork : 
https://github.com/TheCamusean/gym-gazebo

**Comment by mkhansen-intel** [comment]
@TheCamusean - See my proposed changes here (#134 ). I want to make sure that wouldn't conflict with your boilerplate.

**Comment by nzlz** [comment]
Discarded for now, can't maintain this with the upcoming version of gym-gazebo. Closing.
