### ISSUE TITLE
Turtlebot circles aimlessly

### ISSUE THREAD

**Issue by JaxDraxler** [erlerobot/gym-gazebo#129]
Hello !!
I've installed ROS kinetic with Gazebo 8. I've run the setup_kinetic.bash, despite an error in the cmake the turtlebot still managed to boot and episodes started. 
However the turtle-bot seems to just circle aimlessly around itself until the episode terminates, not doing any intelligent action or learning.

Any help please ??

![image](https://user-images.githubusercontent.com/38314657/38667179-0c9b5526-3e41-11e8-998d-b768015c7d18.png)

**Comment by mkhansen-intel** [comment]
Are you running a gzclient? Which maze / map are you using? Can you submit a screenshot of the robot in the maze? I'll be honest I have no idea why the robot would go in circles, but more info might help.

**Comment by JaxDraxler** [comment]
I was running the circuit2 qlearn example.
I have found the issue, it is an error in the setup_kinetic.bash.
You need to CATKIN_IGNORE the wiimote.
Thank you for responding.

**Comment by pulver22** [comment]
HI @JaxDraxler, did you solve? I have the same exact problem!
