### ISSUE TITLE
Support for Erle-Spider

### ISSUE THREAD

**Issue by peterzcc** [erlerobot/gym-gazebo#13]
It seems like Erle-Spider is a good robot for reinforcement learning research, will we have support for that?

**Comment by IkerZamora** [comment]
There is currently no support in Gym-Gazebo for Erle-Spider, since its simulation for Gazebo is not finished. Once that's finished, I agree: it would be a good robot to experiment with in Gym.

**Comment by vmayoral** [comment]
Erle-Spider has actually been discontinued. There're no plans for adding Erle-Spider to the gym.
