### ISSUE TITLE
env.reset Error when running circuit2 DQN

### ISSUE THREAD

**Issue by mkhansen-intel** [erlerobot/gym-gazebo#135]
When running the circuit2 DQN example, I get this error:
```
EP 233 - 98 timesteps - last100 Steps : 213 - Cumulated R: 10.05   Eps=0.31     Time: 1:04:50
reached the end! :D
EP 234 - 1001 timesteps - last100 Steps : 221 - Cumulated R: 2504.8   Eps=0.31     Time: 1:07:07
Traceback (most recent call last):
  File "circuit2_turtlebot_lidar_dqn.py", line 336, in <module>
    observation = env.reset()
  File "/usr/local/lib/python2.7/dist-packages/gym/wrappers/monitor.py", line 37, in reset
    self._before_reset()
  File "/usr/local/lib/python2.7/dist-packages/gym/wrappers/monitor.py", line 185, in _before_reset
    self.stats_recorder.before_reset()
  File "/usr/local/lib/python2.7/dist-packages/gym/wrappers/monitoring/stats_recorder.py", line 68, in before_reset
    raise error.Error("Tried to reset environment which is not done. While the monitor is active for {}, you cannot call reset() unless the episode is over.".format(self.env_id))
gym.error.Error: Tried to reset environment which is not done. While the monitor is active for GazeboCircuit2TurtlebotLidarNn-v0, you cannot call reset() unless the episode is over.
mkhansen@mkhansen-sky1:~/gym-gazebo$ 
```
This logic is checking for steps >= 1000 then doing some printing before breaking out of the steps loop. This doesn't make sense to me as steps is hard-coded to 10,000, so why break out at 1000? Is there a reason for this?

**Comment by yangningbocn** [comment]
I got the same error with you. And  I think 1000 is just the end of the game.Wasting to much time in one EP make learning ineffective.Like the turtlebot run a  little circuit endlessly.
And  do you know why the error occured? Why the environment can't reset?This confused me for a long time.I think we can talk about it.

**Comment by mkhansen-intel** [comment]
Yes, I see that now, I've found the issue is also seen in the upstream project here: https://github.com/openai/gym/issues/430

I'm attempting to get their solution working, but I'm not seeing the env set done=True, even after the 1000 cycle limit is hit (I've also tried it with much lower numbers like 50 or 100). I'll continue to try and debug

**Comment by Mostafa95** [comment]
@mkhansen-intel  I solved this problem by initializing 

 `max_episode_steps=1000`

 in 

> gym-gazebo/gym_gazebo/__init__.py

in the registry of the env I am using. But I think this fix is cleaner. 
One point though, I think the loop  " while not done: " will not terminate as done variable is never set to true. Did you test it ?

**Comment by mkhansen-intel** [comment]
@Mostafa95 - thanks, I appreciate the feedback / input.

**Comment by yangningbocn** [comment]
It works! Thank you all.

**Comment by mkhansen-intel** [comment]
@yangningbocn - I'm glad to hear it works for you!
