### ISSUE TITLE
Support for Atlas Robot

### ISSUE THREAD

**Issue by peterzcc** [erlerobot/gym-gazebo#14]
May I ask if anyone is working on developing a [Atlas robot simulation ](http://gazebosim.org/tutorials?tut=drcsim_atlas_siminterface&cat=drcsim). I will plan to work on that if others haven't started yet, otherwise I would be willing to help.

**Comment by Nestor94Gonzalez** [comment]
No that I'm aware of. It would be great if you could add the Atlas to the gym! If you have any doubts about how to do it I will be willing to help too.

**Comment by vmayoral** [comment]
I can confirm that there's no one in our team working on Atlas but it definitely would be a great contribution.

**Comment by vmayoral** [comment]
Closing this since it's been inactive for a while.
