### ISSUE TITLE
Turtlebot not spawned completly

### ISSUE THREAD

**Issue by JaxDraxler** [erlerobot/gym-gazebo#142]
Hello !!

So i have a running gym-gazebo bridge but having a problem when opening gzclient.

I can only see the LIDAR and not the turtlebot !!

![image](https://user-images.githubusercontent.com/38314657/39248928-b6c2ea4e-489d-11e8-8d2f-30c9db5fa38c.png)

There is no raised error or issue. Any ideas on what might be going on ?

Thank you

**Comment by pmwenzel** [comment]
Hi,

did you make sure that you have all the turtlebot/turtlebot_create/turtlebot_simulator packages in your catkin workspace? This can be an issue. What ROS/Gazebo configuration are you using?

**Comment by JaxDraxler** [comment]
@pmwenzel Hello !!

I am using ROS kinetic with gazebo 8.4

Yes i think all packages are present in my workspace if i am not mistaking !!

![image](https://user-images.githubusercontent.com/38314657/39305016-f3ce37f4-495b-11e8-96c9-837f52c6028c.png)

**Comment by geerfing** [comment]
Hi,
I have a running  gym-gazebo ,but it didn't appear the environment,how should I do .
Thank you!

**Comment by JaxDraxler** [comment]
@geerfing Hello!! There should be a raised error somewhere when you run the code that might help figure out what is the problem
