### ISSUE TITLE
Circuit2_turtlebot_lidar_dqn.py stuck and doesn't run

### ISSUE THREAD

**Issue by aunsid** [erlerobot/gym-gazebo#146]
I have already applied the fixes discussed in issues  #89 #97 #101 #110 #113 #116 #121 #125 #144 etc. and was led nowhere by issues #86 #82 #74 #108 #122 etc. Whenever I try running this example, the terminal shows:
![issue](https://user-images.githubusercontent.com/34586854/39463309-8d9b6a52-4cd4-11e8-9c62-1babdb0c33e4.png)

and nothing happens. Even in the gzclient the turtlebot gets stuck in one place rotating extremely slowly  and makes no progress after 8 additional hours of processing. This happens with all of the dqn example files. For those files that do run, (qlearn.py files) they all crash after 1 to 3500 iterations spewing another problem for which I have yet to find a submitted issue (anywhere, not just on this posting) which wasn't closed prior to seeing a proper answer posted:

void gazebo::sensors::SensorManager::SensorContainer::RunLoop(): Assertion `(diffTime.sec < 1)&&("Took over 1.0 seconds to update a sensor.")' failed.

I've been working on just making something converge for about 60 hours now, to no avail. Please help!

**Comment by mkhansen-intel** [comment]
Hi @aunsid. Can you show what commands you ran (turtlebot_setup.bash, etc) and copy & paste the info from your screen from the last command you typed to this point above. It is likely there is an error message that already scrolled off-screen above your screenshot. If you can give more info, I'll try to help. You shouldn't have to run for 60 hours. You should be able to see progress in the form of Episode summaries right away.

**Comment by aunsid** [comment]
![bash](https://user-images.githubusercontent.com/34586854/39489795-f44756a2-4d43-11e8-8139-f15739949264.png)
![export_ros](https://user-images.githubusercontent.com/34586854/39489798-f6dde778-4d43-11e8-9623-074fa0632440.png)
![monitor](https://user-images.githubusercontent.com/34586854/39489803-f9b4c3d6-4d43-11e8-9a18-36df868e1aa3.png)
![kob](https://user-images.githubusercontent.com/34586854/39489806-fbb04f8e-4d43-11e8-91dd-e8eeb960462a.png)

And another problem that I have faced while running other algorithms search as q-learn, I either get an error saying something about env.reset() or one of the sensors stops working. It has never been able to run all 10,000 episodes. 3000 at max.
Thanks!

**Comment by geerfing** [comment]
I  have  the same question, I still don't  solve it now

**Comment by aunsid** [comment]
Could you please make a README file for python2 ?

**Comment by zacwellmer** [comment]
@aunsid Did you end up sorting this out?

**Comment by aunsid** [comment]
Well yeah, by installing it on on python2. Although I havent been able to complete 1000 epochs cause i get some kind of an error stating that one of the sensors took too long to respond, resulting in a core dump.

**Comment by aunsid** [comment]
@mkhansen-intel does the camera_dqn.py work for you?

**Comment by zacwellmer** [comment]
yeah, that is exactly the problem I am running into with the circuit_turtlebot_lidar_qlearn.py script. @aunsid  issue #148 w/ instructions is how I managed to get to this point.

Below is the core dump I'm running into(sounds the same as yours)
```
gzserver: /build/gazebo-nhSAPd/gazebo-7.0.0+dfsg/gazebo/sensors/SensorManager.cc:545: void gazebo::sensors::SensorManager::SensorContainer::RunLoop(): Assertion `(diffTime.sec < 1)&&("Took over 1.0 seconds to update a sensor.")' failed.
Aborted (core dumped)
[gazebo-1] process has died [pid 9240, exit code 134, cmd /home/zacwellmer/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/gazebo_ros_pkgs/gazebo_ros/scripts/gzserver -e ode /home/zacwellmer/gym-gazebo/gym_gazebo/envs/installation/../assets/worlds/circuit.world __name:=gazebo __log:=/home/zacwellmer/.ros/log/7cca1d54-54c7-11e8-b9d4-000c299ea188/gazebo-1.log].
log file: /home/zacwellmer/.ros/log/7cca1d54-54c7-11e8-b9d4-000c299ea188/gazebo-1*.log
```

**Comment by aunsid** [comment]
I was able to get qlearn to work just fine. Try running it circuit_turtlebot_lidar_qlearn.py  -j(no of cores)
so if you have 6 cores it'll be circuit_turtlebot_lidar_qlearn.py -j6. Have the system monitor on, and DONT run gzclient in another terminal. I think its a processor issue. Cause I stopped all my other tasks and was able to get to more episodes with no other processes running in the background.

**Comment by zacwellmer** [comment]
still crashes on me. Perhaps it's because I'm using a VM? But I give the VM 3 cores and only specify using 1 core to the circuit_turtlebot_lidar_qlearn.py script

**Comment by aunsid** [comment]
I was using Intel  Xeon(R) CPU E3-1271, it had eight cores.

**Comment by mkhansen-intel** [comment]
@aunsid - I haven't tried running the 'camera' version.

**Comment by ElizabethDuo** [comment]
@zacwellmer Hi Zac! I also met the core dump problem when running `python circuit_turtlebot_lidar_qlearn.py `. Have you solved this problem? Any good ideas?
