### ISSUE TITLE
a error in turtlebot_camera_dqn

### ISSUE THREAD

**Issue by SelinaChe** [erlerobot/gym-gazebo#15]
When I run script circuit2c_turtlebot_camera_dqn.py in docker, it occurs to "[spawn_turtlebot_model-2]" and the log shows "SpawnModel: Model pushed to spawn queue, but spawn service timed out waiting for model to appear in simulation under the name mobile_base". Could you please tell me how to solve it?

**Comment by imuguruza** [comment]
Please refer to our [forum](http://forum.erlerobotics.com/), this is where we focus all our technicall issues.
