### ISSUE TITLE
strangely unbale to register the node when i run the circuit2_turtlebot_lidar_dqn.py

### ISSUE THREAD

**Issue by zengjie617789** [erlerobot/gym-gazebo#150]
i meet the problem when i run my rivised code,i thought i was because of my own code ; but when i git pull the new code and run it again ,it meet the same problem, anyone who can help me ,please!
i doubt if my keras gpu config is not correct. here are  my screenshots blow:
 

![image](https://user-images.githubusercontent.com/25050291/39792347-b66682e2-5372-11e8-9f42-a3336707a33d.png)

```

[global]
floatX = float32
device = cuda0

[gpuarray]
gpuarray.preallocate = 0.8
```

**Comment by mkhansen-intel** [comment]
@zengjie617789 - if you open another window and run 'top' do you see the rosmaster node running? It looks to me like it has died somehow.

**Comment by zengjie617789** [comment]
@mkhansen-intel  yes,it's still running 
![image](https://user-images.githubusercontent.com/25050291/39901570-f29d987e-54fb-11e8-9253-883791f90dd6.png)

**Comment by mkhansen-intel** [comment]
@zengjie617789 - are you running turtlebot_setup_nn.bash first? Are you getting the error at the same time every time you run? What exact commands are you running to start the example? Have you tried without your modified code first and does that work?

**Comment by zengjie617789** [comment]
@mkhansen-intel  yes ,i run it without my modified code ,but it still got the same problem. I have run turtlebot_setup_nn.bash first. when i enter the floder,i found the file "turtlebot_cnn_setup.bash", should i run it ?

**Comment by nzlz** [comment]
@zengjie617789  `turtlebot_cnn_setup.bash` sets the corresponding environment variables to work with the turtlebot CNN example, not NN (not using the convolutional network required to work with vision). If you are still interested in this matter please open a **Advice request** issue to facilitate issue-tracking.
