### ISSUE TITLE
ImportError: no module named gym_gazebo

### ISSUE THREAD

**Issue by hlinh0411hd** [erlerobot/gym-gazebo#152]
Hi, I have a problem: even though I installed gym-gazebo as the instruction, when I run example, I still get that error: `ImportError: no module named gym_gazebo`
![image](https://user-images.githubusercontent.com/17883390/39963783-a3b4098c-569f-11e8-9d87-1923e92b6107.png)
I check in pip list, there is gym_gazebo package. Can someone help me?

**Comment by zengjie617789** [comment]
have you tried to open a new terminal and source it?

**Comment by ElizabethDuo** [comment]
I tried it again and showed up a more detailed error info.
![default](https://user-images.githubusercontent.com/31089745/42940946-b1567174-8b8d-11e8-82a7-8e94dee67f66.png)

**Comment by hlinh0411hd** [comment]
Sorry. I dont remember exactly. One of my solution is copying file example to another folder. And the last option is reinstalling gym gazebo. Hope it help.

**Comment by hlinh0411hd** [comment]
I got troubles with sudo and non-sudo, python 2 and 3, pip2 and pip3. And I usually have to reinstall all

**Comment by ElizabethDuo** [comment]
Thanks for the advice!
I tried reinstall it but I don't sure about am I do this right.How did you reinstall gym gazebo? I tried `pip uninstall gym-gazebo` and it didn't work so I deleted the old folder and re-downloaded it and did `pip install -e` again. This is the info after reinstall.
![default](https://user-images.githubusercontent.com/31089745/43000978-1dc9806c-8c56-11e8-9aa9-e0e163ef6faa.png)
Do you have the same info after reinstall it? It seems like it didn't uninstall it completely before reinstall.

**Comment by ElizabethDuo** [comment]
I solved this problem by `sudo pip install --upgrade gym`.
Hope this can be helpful.
