### ISSUE TITLE
The turtlebot  didn't move 

### ISSUE THREAD

**Issue by geerfing** [erlerobot/gym-gazebo#154]
Hello! I run the command :python3 circuit2c_turtlebot_camera_dqn.py
The  turtlebot  didn't move,how should I  solve it? It appears  like  this:
![2018-05-15 11-02-56](https://user-images.githubusercontent.com/23430298/40034605-43fa7ba6-5830-11e8-9c44-10e45b494d00.png)
![2018-05-15 10-58-48](https://user-images.githubusercontent.com/23430298/40034629-52104a36-5830-11e8-9266-5559ac75b803.png)

**Comment by radisc** [comment]
having the same problem

**Comment by pulver22** [comment]
Same here! Did anyone solve it?

**Comment by nzlz** [comment]
I remember we had this same issue when we implemented this solution and we managed to fix it. I will try to look at it when I have time because right now I can't remember, but for sure we did not use python3. Also make sure to perform a clean installation. @IkerZamora any idea?

**Comment by nzlz** [comment]
Issue related to the usage of python3. Please stick to python2 or fill a **Feature request** issue to facilitate issue-tracking. However, note that right now there are not plans to enable python3 for the turtlebot.
