### ISSUE TITLE
X_batch = np.empty((0,self.input_size), dtype = np.float64) what is the meaning of 0

### ISSUE THREAD

**Issue by geerfing** [erlerobot/gym-gazebo#156]
![2018-05-23 14-54-32](https://user-images.githubusercontent.com/23430298/40409773-75f47e6c-5e9e-11e8-9a76-8971aece593d.png)
I want to know why the number is 0,np.empty((0,self.input_size), dtype = np.float64) 
![2018-05-23 15-36-09](https://user-images.githubusercontent.com/23430298/40409952-092a3960-5e9f-11e8-8bbd-8ce21055284c.png)
Thanks!

**Comment by zengjie617789** [comment]
～generate a matrix which of row is one and column is input_size

**Comment by zengjie617789** [comment]
@geerfing yes i think you are right ,but this make me think what is the function of "X_batch"?

**Comment by nzlz** [comment]
If you are still interested in this matter, please fill an **Advice request** issue to facilitate issue-tracking.
