### ISSUE TITLE
why the bumper in turtlebot env dosen't work?

### ISSUE THREAD

**Issue by flutist** [erlerobot/gym-gazebo#158]
I publish the topic of /mobile_base/events/bumper, but it doesn't publish anything in the terminal either the turtlebot crash with something in enviroment. please help me, it is very important question for me.

**Comment by flutist** [comment]
Is anybody could help me

**Comment by nzlz** [comment]
Sorry for the late reply @flutist! If you are still facing this problem please open a **Bug report** or **Advice request** issue to facilitate issue-tracking.
