### ISSUE TITLE
Stuck in the circuit2_turtlebot_lidar_qlearn.py example

### ISSUE THREAD

**Issue by TPEmist** [erlerobot/gym-gazebo#159]
Since I'm trying to run the example 
 `$ python3 circuit2_turtlebot_lidar_qlearn.py`

But coming up with the error [problem1]:

>while processing /home/user/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/turtlebot_gazebo/launch/includes/kobuki.launch.xml:
Invalid <arg> tag: turtlebot_description
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/user/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share. 
Arg xml is <arg default="$(find xacro)/xacro.py '$(find turtlebot_description)/robots/$(arg base)_$(arg stacks)_$(arg 3d_sensor).urdf.xacro'" name="urdf_file"/>
The traceback for the exception was written to the log file

>>
.
.
_### and also try this solution below:
https://github.com/erlerobot/gym-gazebo/issues/58
but still not work
please help_
>>
.
.
update:
I edit my kobuki.launch.xml to something like below and it turn out to solve the problem 1 ,
```xml
<launch>
  <arg name="base" default="kobuki_"/>
  <arg name="stacks" default="hexagons_"/>
  <arg name="3d_sensor" default="asus_xtion_pro"/>
  <!--arg name="urdf_file" default="$(find xacro)/xacro.py '$(find turtlebot_description)/robots/$(arg base)$(arg stacks)$(arg 3d_sensor).urdf.xacro'"/-->
  <arg name="urdf_file" default="$(find xacro)/xacro.py '$(find turtlebot_description)/robots/kobuki_hexagons_$(arg 3d_sensor).urdf.xacro'"/>
```
....
but then I got another problem:
since I run `$ python3 circuit2_turtlebot_lidar_qlearn.py`
and it always stuck at this line below:
> [ INFO] [1529091618.763671792, 89.110000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""

CAN ANYONE HELP?

![](https://preview.ibb.co/efBtkJ/1.png)
![](https://preview.ibb.co/jwm4sy/2.png)

**Comment by zengjie617789** [comment]
you should source your workplace or add the path into the ~/.bashrc

**Comment by nzlz** [comment]
Hi @TPEmist sorry for the late reply! You should be using python2. We are not planning to migrate the Turtlebot to python3, but if you want to share your thoughts or any other kind of problem, please fill a **Feature resquest** of **Bug request** issue to facilitate issue-tracking.
