### ISSUE TITLE
installing openCV issue

### ISSUE THREAD

**Issue by srkamo** [erlerobot/gym-gazebo#160]
Following this page (https://docs.opencv.org/3.4.1/d2/de6/tutorial_py_setup_in_ubuntu.html) to install openCV and I cannot get the import to work.

The instructions I tried were 
`sudo apt-get install python-opencv`

then to verify it works it states to do:
`import cv2 as cv
print(cv.__version__)`

I get this response when I try to import:
`>>> import cv2 as cv`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
```
`ImportError: /opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type
`
I have unset my python path but then I do not have access to rospy and other libraries like numpy.

Any suggestions are greatly appreciated.

**Comment by zengjie617789** [comment]
"rename cv2.so to another name(cv2-renamed.so) at /opt/ros/kinetic/lib/python2.7/dist-packages/"
you should follow the instruction step by step

**Comment by srkamo** [comment]
thank you
