### ISSUE TITLE
 Pycharm cannot run the examples, "import roslaunch ;no module named defusexml"

### ISSUE THREAD

**Issue by zengjie617789** [erlerobot/gym-gazebo#161]
when i run the py file UNDER Pycharm , it shows the error "FileNotFoundError: [Errno 2] No such file or directory: 'roscore'"

1.it can run under the terminal successfully，
![image](https://user-images.githubusercontent.com/25050291/42135144-856619ba-7d79-11e8-8280-e98eb5ee003c.png)
 but meet erros under Pycharm:
![image](https://user-images.githubusercontent.com/25050291/42135163-9d49d42c-7d79-11e8-96a2-e3ea9e57b0ea.png)
2.the path of virtuanenv in Pycharm is 
![image](https://user-images.githubusercontent.com/25050291/42135176-b81c5edc-7d79-11e8-8e3c-5c37f587a7f9.png)
anyone who can help ? 

----------------------------------
![image](https://user-images.githubusercontent.com/25050291/42452834-b3f10a70-83bd-11e8-9ba4-58c4a22fd8b6.png)

when i under Python3 it can not import roslauch but under Python2 it can

what make me mad is it can run successfully with my lap-computer ~~~

thank you in advance~

**Comment by pmwenzel** [comment]
You should make sure that you run PyCharm from the terminal to make sure your .bashrc is initialised correctly, hence sourcing your ROS environment. Hope that helps.

**Comment by zengjie617789** [comment]
@pmwenzel   I did what you said. I follow the advice that to add something in the Jetbranis-pycharm.desktop; as show blow :   
![image](https://user-images.githubusercontent.com/25050291/42225248-adfe6850-7f0e-11e8-80b8-025e8913303e.png)
the file of .bashrc  was :  
![image](https://user-images.githubusercontent.com/25050291/42225330-e12c744c-7f0e-11e8-80e6-5f52bf51b769.png)
 and  what puzzled me is i can import rospy successfully in the Pycharm~
 
could you give me some other advice? thank you~

**Comment by pmwenzel** [comment]
I don't know either. Maybe some of your ROS dependencies are screwed up or do you only get the errors when running from PyCharm?

**Comment by zengjie617789** [comment]
the Environment Variables make me mad ~~~~~~~~~~~~

![image](https://user-images.githubusercontent.com/25050291/42419599-f275aaea-82ea-11e8-82ae-40df4a36a848.png)

**Comment by nzlz** [comment]
Hi @zengjie617789 , if you still need help with this matter please fill a **Advice request** issue to facilitaty issue-tracking.
