### ISSUE TITLE
tagged gym-gazebo repo to work with Dockerfile

### ISSUE THREAD

**Issue by mwagyuvm** [erlerobot/gym-gazebo#163]
I'm trying to build the gym-gazebo docker image ("docker build -t gym-gazebo ." from the root of this repository, using the included Dockerfile) but run into an issue in step 24, "RUN cd ~/ros_catkin_ws && wstool init -j1 src kinetic-ros_comm-wet.rosinstall" as follows.

```
Step 24/125 : RUN cd ~/ros_catkin_ws && wstool init -j1 src kinetic-ros_comm-wet.rosinstall
 ---> Running in 0489b1a426b5
Using initial elements from: kinetic-ros_comm-wet.rosinstall
Writing /root/ros_catkin_ws/src/.rosinstall
ERROR [vcstools] Tarball download unpack failed: file could not be opened successfully[/vcstools]
ERROR [vcstools] Tarball download unpack failed: file could not be opened successfully[/vcstools]
ERROR [vcstools] Tarball download unpack failed: file could not be opened successfully[/vcstools]
ERROR [vcstools] Tarball download unpack failed: file could not be opened successfully[/vcstools]
```
I don't see any tags in this repo. Are there points at which the gym-gazebo has been tested to have successful docker builds so I can work from those and have a working gym-gazebo container up quickly?

**Comment by AustinDeric** [comment]
@mwagyuvm I can confirm that the Dockerfiles are not building.  I am working on an update, should be ready this week.  see issue #96

**Comment by mwagyuvm** [comment]
Very good news. Please let me know if I can help in any way.

**Comment by nzlz** [comment]
Lets follow this at https://github.com/erlerobot/gym-gazebo/issues/96 .
