### ISSUE TITLE
How can I set a navigation goal in maze environment for turtlebot?

### ISSUE THREAD

**Issue by ElizabethDuo** [erlerobot/gym-gazebo#166]
I want to add a navigation goal in maze environment and change unoriented  walk to oriented navigation. Any good ideas to do that? How can I publish navigation target msgs and show the navigation goal in maze?
Many thanks!!

**Comment by pmwenzel** [comment]
You can simply set a x and y coordinate corresponding to your goal location. 

Use the following subscriber to get the current x and y position of the robot:
```
rospy.Subscriber(name='/gazebo/model_states', data_class=ModelStates,
                                             callback=self.position_callback)
```

Either you are working on RL, you should adopt your reward function accordingly or you use a planner like A*. Hope that helps. You can visually set an object to your goal location in gazebo if you want to.

**Comment by yangchen12** [comment]
> You can simply set a x and y coordinate corresponding to your goal location.
> 
> Use the following subscriber to get the current x and y position of the robot:
> 
> ```
> rospy.Subscriber(name='/gazebo/model_states', data_class=ModelStates,
>                                              callback=self.position_callback)
> ```
> Either you are working on RL, you should adopt your reward function accordingly or you use a planner like A*. Hope that helps. You can visually set an object to your goal location in gazebo if you want to.

Hello,how can konw if the robot reaceh the goal by the code?

**Comment by pmwenzel** [comment]
Just check the squared distance between your goal point and the actual location of the robot and compare it with some threshold. This should be the easiest way.

**Comment by yangchen12** [comment]
> Just check the squared distance between your goal point and the actual location of the robot and compare it with some threshold. This should be the easiest way.
Can you help with the code?Many thanks!!

**Comment by yangchen12** [comment]
> Hi @yangchen12 ,
> 
> I believe you should change the `_step(..) `function in your environment so that it returns the boolean final state if the robot reaches the position (done/ not done). @pmwenzel has already mentioned a good way to calculate if the goal position if correct or not.
> 
> About the specific code, a quick google search will provide you with the code you need. Please share your own code if you have more specific issues.

Many thanks!!If I have questions,I will ask you for your help.Many thanks!!
