### ISSUE TITLE
 "Could NOT find kdl_conversions" when "processing catkin package: 'kobuki_auto_docking'"

### ISSUE THREAD

**Issue by ElizabethDuo** [erlerobot/gym-gazebo#169]
![2018-08-07 21-32-09](https://user-images.githubusercontent.com/31089745/43778979-b9addf64-9a89-11e8-954a-7120a1bdba6b.png)
It seems like it is lacking of kdl_conversions pkg.
So I went to [https://github.com/rock-control/control-kdl_conversions](url) and  [https://github.com/aur-archive/ros-groovy-kdl-conversions](url), then added the file to /gym_gazebo/envs/installation/catkin_ws/src, none of them worked.
I wonder if I can catkin ignore kobuki_auto_docking, because turtlebot is the main robot I use.
Any good idea to slove this?
Thanks!!

**Comment by nzlz** [comment]
Sorry for the late reply @ElizabethDuo , if you are still facing this problem please fill a **Bug report** issue to facilitate issue-tracking.
