### ISSUE TITLE
when I set the gazebo (GPU),I  couldn't solve the question as followed: 

### ISSUE THREAD

**Issue by geerfing** [erlerobot/gym-gazebo#170]
![image](https://user-images.githubusercontent.com/23430298/44069582-0b587e28-9fb2-11e8-8de8-6fdf603bac02.png)

**Comment by nzlz** [comment]
Sorry for the late reply @geerfing ! Earlier gazebo versions where known to have this kind of gpu-related Bug, which was solved trying to launch gazebo a couple of times. This should not happen anymore. But if you are still facing this problem please fill a **Bug report** issue to facilitate issue-tracking.
