### ISSUE TITLE
Is it possible to work it in conda environrment?

### ISSUE THREAD

**Issue by Geonhee-LEE** [erlerobot/gym-gazebo#173]
Hello.

I have wanted to adapt reinforcement learning to the GAZEBO.

However, When I follow your [INSTALL.md](https://github.com/erlerobot/gym-gazebo/blob/master/INSTALL.md), It didn't work.

My develop environment is Ubuntu16.04 and ros-kinetic.

I create the virtual environment using Conda like this conda create -n tensorflow pip python=3.5.1

I installed every process such as Theano, gym, Keras..

But, when I commanded `bash setup_kinetic.bash`, It had error...

Who you know what it is problems?		

I really want to use gym-gazebo.

Thanks you for your interest.

**Comment by ahcorde** [comment]
Unfortunately installing `gym-gazebo` is not a straightforward process. If you post your errors we can try to help you.

**Comment by Geonhee-LEE** [comment]
Thanks @ahcorde  
I just uploaded the picture.

![screenshot from 2018-08-28 00-04-30](https://user-images.githubusercontent.com/12562147/44667615-394c2100-aa56-11e8-8e8d-74dafd514df4.png)

when I commanded `bash setup_kinetic.bash` in the installation folder, I saw "Package "mav_msgs" not found in the workspace

**Comment by ahcorde** [comment]
Look at this: `Packages "mav_msgs" not found in the workspace`

You need to include this [package](https://github.com/ethz-asl/mav_comm) into your workspace
