### ISSUE TITLE
Customize robot

### ISSUE THREAD

**Issue by rahulindoria5** [erlerobot/gym-gazebo#177]
Hi All, 
Can we use a customized robot in gym-gazebo with a customized environment? If yes, then how will we define an environment?

**Comment by nzlz** [comment]
Hi @rahulindoria5 ,

Yes, you can use any customized robot in gym-gazebo if you use ROS as middleware. You should follow the example environments available, the Turtlebot is a good starting point i think. Just try to adapt the code for your own project.

If you have created a robot in gazebo from scratch, or you want to do that, you should create the ros plugins required to interact with the robot. If you want more information regarding this specific purpose, email me and I will send you some code examples.
