### ISSUE TITLE
AttributeError: 'filter' object has no attribute 'insert'

### ISSUE THREAD

**Issue by andjsmile** [erlerobot/gym-gazebo#179]
Traceback (most recent call last):
  File "/home/parallels/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/xacro/xacro.py", line 60, in <module>
    import xacro
  File "/home/parallels/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/devel/lib/python3/dist-packages/xacro/__init__.py", line 12, in <module>
    sys_path.insert(0, p)
AttributeError: 'filter' object has no attribute 'insert'
while processing /home/parallels/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/turtlebot_simulator/turtlebot_gazebo/launch/includes/kobuki.launch.xml:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/home/parallels/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/xacro/xacro.py '/home/parallels/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/turtlebot/turtlebot_description/robots/kobuki_hexagons_asus_xtion_pro.urdf.xacro'] returned with code [1]. 

Param xml is <param command="$(arg urdf_file)" name="robot_description"/>
The traceback for the exception was written to the log file

**Comment by nzlz** [comment]
Hi @andjsmile , sorry for the late reply! if you are still facing this problem please fill a **Bug report** issue to facilitate issue-tracking.
