### ISSUE TITLE
ErleCopter reset - mavros, Gazebo killed

### ISSUE THREAD

**Issue by shohinm** [erlerobot/gym-gazebo#18]
While running the `erlecopter_hover_qlearn.py`, the ErleCopter gets armed and takes off successfully. But right after, the `env.reset()` function is called. The call stack then proceeds into `_reset() -> _relaunch_apm()` in `gazebo_erlecopter_hover.py`. This function seemingly should kill and restart a whole bunch of processes, however it always also kills mavros and Gazebo which brings the whole simulation to a halt. The error messages towards the end are:

> Takeoff successful
> [ERROR] [1491403829.728239248, 96.447500000]: tcp0: receive: End of file
> terminate called after throwing an instance of 'std::system_error'
>   what():  Resource deadlock avoided
> sh: 1: kill: No such process
> 
> Waiting for mavros...
> [ INFO] [1491403829.835096238, 96.465000000]: ARI: Ardupilot connection off, no messages
> 
> REQUIRED process [mavros-1] has died!
> process has died [pid 24127, exit code -6, cmd /home/shohin/Libraries/simulation/ros_catkin_ws/devel/lib/mavros/mavros_node __name:=mavros __log:=/home/shohin/.ros/log/1caf69fe-1a0f-11e7-a0c1-08d40c58bed9/mavros-1.log].
> log file: /home/shohin/.ros/log/1caf69fe-1a0f-11e7-a0c1-08d40c58bed9/mavros-1*.log
> Initiating shutdown!
> 
> 
> [gazebo_gui-4] killing on exit
> [gazebo-3] killing on exit
> [mavros-1] killing on exit
> [ INFO] [1491403830.235859820, 96.465000000]: ARI: Exited listening loop for Ardupilot messages
> [gazebo-3] escalating to SIGTERM
> shutting down processing monitor...
> ... shutting down processing monitor complete
> done

The `mavros-1.log` is not written to disk, so I cannot seem to debug anything from there. Is there a solution to this issue?

**Comment by vmayoral** [comment]
No further support for Erle-Copter envs will be given.
