### ISSUE TITLE
No module named gym_gazebo 

### ISSUE THREAD

**Issue by taihirose** [erlerobot/gym-gazebo#183]
I have a same problem(https://github.com/erlerobot/gym-gazebo/issues/152).
I can't slove this. Sorry my poor English. Please tell me.

![github](https://user-images.githubusercontent.com/35332761/48409336-e34a6800-e77e-11e8-948e-abb8a5daa417.png)

**Comment by nzlz** [comment]
Hi @taihirose,
First thing, i recommend you go back to your home directory `cd ~` before you clone the gym-gazebo repo in [this ](https://github.com/erlerobot/gym-gazebo#running-an-environment)step, and keep following the installation steps from that point. Also note that gym and gym-gazebo are different packages.

**Comment by taihirose** [comment]
Thank you for your answer!!
But same error display.
Do you have any solutions?

**Comment by taihirose** [comment]
I have reinstalled,and this error display.What does this mean?
/home/hirose/ピクチャ/Screenshot from 2018-11-15 19-25-52.png

**Comment by taihirose** [comment]
I have reinstalled,and new error display.What does this mean?
![screenshot from 2018-11-15 19-25-52](https://user-images.githubusercontent.com/35332761/48547080-263a4600-e90d-11e8-9fd4-7c733e0547df.png)

**Comment by taihirose** [comment]
This Usage step(https://github.com/erlerobot/gym-gazebo#running-an-environment)solve the error.
I overlook that.

The simulator have launched,but turtlebot can't reinforcement learning.
It looks like it is slipping on Gazebo.And reward plot can't display.
Please heip me!! I'm sorry to bother you over and over.

**Comment by taihirose** [comment]
Screenshot here.
![screenshot from 2018-11-15 21-41-07](https://user-images.githubusercontent.com/35332761/48554112-dbc2c480-e920-11e8-8ea8-239065909ad5.png)

**Comment by taihirose** [comment]
OK. Thank you for answering the question. I'll do my best.

**Comment by nzlz** [comment]
Hello again @taihirose . I have researched a bit about the display_plot error, related to the wrapper. You simply have to add the following import [here](https://github.com/erlerobot/gym-gazebo/blob/a545e7bbd3bcc5d0fd9c012d0bc42dab7324c579/examples/turtlebot/circuit2_turtlebot_lidar_dqn.py#L8):
`from gym import wrappers`. It will work this way :)

**Comment by sayment** [comment]
I solved the same problem with the following command below

`cd ~/gym-gazebo
sudo -H pip install -e .`

**Comment by nzlz** [comment]
Solved, closing.
