### ISSUE TITLE
How to add more turtlebot into the gazebo environment ?

### ISSUE THREAD

**Issue by Jen-Hao-Henry-Cheng** [erlerobot/gym-gazebo#184]
I want to add one or two turtlebots in GazeboCircuit2TurtlebotLidar-v0, and train these three robots avoid to hit the wall and also other turtlebots. But I am beginner in ROS and Gazebo. Could anyone give me some help or reference?

**Comment by nzlz** [comment]
Sorry for the late reply @Jen-Hao-Henry-Cheng ! if you are still interested in this please fill a **Advice request** issue to facilitate issue-tracking.
