### ISSUE TITLE
Install Turtlebot_gazebo

### ISSUE THREAD

**Issue by ColeKOP** [erlerobot/gym-gazebo#19]
After I install the Gazebo7 using "sudo apt-get remove .*gazebo.* && sudo apt-get update && sudo apt-get install gazebo7 libgazebo7-dev", and run "python circuit2_turtlebot_lidar_qlearn.py", the programs says there is no "turtlebot_gazebo" package. But this package is only compatible with gazebo2 instead of gazebo7. Could anyone help me on this? Thanks in advance.

**Comment by Zhang-Yong** [comment]
Remove gazebo7, reinstall gazebo2.2 by sudo apt-get install ros-indigo-gazebo will fix this issue
