### ISSUE TITLE
Turtlebot installation with gym-gazebo

### ISSUE THREAD

**Issue by omkarpatil18** [erlerobot/gym-gazebo#193]
The official installation requires Gazebo 8 with Kinetic devel. I have followed [this](https://github.com/erlerobot/gym-gazebo/issues/90#issue-290855439). 
To make the turtlebot examples work, we need to compile turtlebot from source right? I followed [this](https://github.com/turtlebot/turtlebot_simulator/issues/67#issuecomment-312432495) for doing that, but was met with errors.
So in the end I have 2 catkin workspaces, one for turtlebot packages, and another in gym-gazebo and I source them both using ~/.bashrc. Am I getting this right?
On a side note, how stable/navigable is melodic with gazebo 9 if I intend to work on turtlebot ?

**Comment by nzlz** [comment]
Hi @omkarpatil18 ,

First of all, you should continue the issue you mention if you followed those steps, not open a new one.

About **ros-melodic**. If you take a look at the installation instructions, you will find that `turtlebot_setup.bash` is in charge of creating and building the workspace. You can take a look at [that file](https://github.com/erlerobot/gym-gazebo/blob/master/gym_gazebo/envs/installation/setup_melodic.bash) if you want to replicate the installation following other instructions. 


> On a side note, how stable/navigable is melodic with gazebo 9 if I intend to work on turtlebot ?

More stable that the approach you are following for sure. Take a look at [this](https://github.com/erlerobot/gym-gazebo/blob/master/INSTALL.md#ubuntu-1804). Python2 is recommended.

I suggest you follow the official instructions for melodic. But if you want to try Python3 for some reason, please share the exact error you are having and I will try to help.
