### ISSUE TITLE
New Environment?

### ISSUE THREAD

**Issue by marooncn** [erlerobot/gym-gazebo#197]
Hi, in gym-gazebo there are only two simple, static mazes to train the Turtlebot to navigate, but with the development of Reinforcement Learning, the generalization is more and more important, is there more complex, dynamic or multiple mazes and diverse input(such as RGB, depth image) for agent to train for navigating?

**Comment by nzlz** [comment]
There is also an colored version of `circuit2`, also static. Right now we can't focus in developing more environments for the Turtlebot, so please feel free to create your own. It is quite an easy task to do so with the gazebo GUI, a bit more complex to create dynamic ones of course.
