### ISSUE TITLE
Create Dockerfile with all steps to install the environment

### ISSUE THREAD

**Issue by LanderU** [erlerobot/gym-gazebo#204]
**Robot**
NONE
**Feature description**

I would like to keep the Dockerfile updated with the real instructions. I can work on this, using the Dockerfile the rest of the people can see (and reproduce it locally) how to install and deploy the environment.

What do you think @nzlz?

**Comment by nzlz** [comment]
Sure! it is a good idea, but you are talking about the upcoming version right? I think we should focus our efforts on that one.

**Comment by rkojcev** [comment]
Let's focus on the new release and create proper dockerfiles for that one.

**Comment by LanderU** [comment]
Done for upcoming version.
