### ISSUE TITLE
Can't find cwiid.h 

### ISSUE THREAD

**Issue by silverjoda** [erlerobot/gym-gazebo#33]
I've tried doing setup.bash on both of my computers now and in both cases the compilation stops at not being able to find <cwiid.h>. Can someone tell me why this is or how I can find this package? So far I've not had any luck. I followed everything according to the instructions.

**Comment by jeasinema** [comment]
For OS using `APT` as package manager:
`sudo apt-get install libcwiid-dev`
can fix this problem.
