### ISSUE TITLE
catkin_make -j4 failed when import and build dependencies

### ISSUE THREAD

**Issue by gmy2013** [erlerobot/gym-gazebo#34]
When I run the setup.bash,it always corrupted in the process of  catkin_make,and shows"E....E.......E.....",
and when I run catkin_make next time,the problem below occurs,plase help me,thanks in advance!

/home/robot/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/drcsim/drcsim_gazebo_plugins/src/DRCVehiclePlugin.cc:924:27: error: ‘class gazebo::physics::Joint’ has no member named ‘SetParam’
       this->frWheelJoint->SetParam("stop_cfm", 0, 1.0);
                           ^
/home/robot/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/drcsim/drcsim_gazebo_plugins/src/DRCVehiclePlugin.cc:927:27: error: ‘class gazebo::physics::Joint’ has no member named ‘SetParam’
       this->blWheelJoint->SetParam("stop_cfm", 0, 0.0);
                           ^
/home/robot/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/drcsim/drcsim_gazebo_plugins/src/DRCVehiclePlugin.cc:929:27: error: ‘class gazebo::physics::Joint’ has no member named ‘SetParam’
       this->blWheelJoint->SetParam("stop_cfm", 0, 1.0);
                           ^
/home/robot/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/drcsim/drcsim_gazebo_plugins/src/DRCVehiclePlugin.cc:932:27: error: ‘class gazebo::physics::Joint’ has no member named ‘SetParam’
       this->brWheelJoint->SetParam("stop_cfm", 0, 0.0);
                           ^
/home/robot/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/drcsim/drcsim_gazebo_plugins/src/DRCVehiclePlugin.cc:934:27: error: ‘class gazebo::physics::Joint’ has no member named ‘SetParam’
       this->brWheelJoint->SetParam("stop_cfm", 0, 1.0);
                           ^
make[2]: *** [drcsim/drcsim_gazebo_plugins/CMakeFiles/DRCVehiclePlugin.dir/src/DRCVehiclePlugin.cc.o] 错误 1
make[1]: *** [drcsim/drcsim_gazebo_plugins/CMakeFiles/DRCVehiclePlugin.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
Linking CXX shared library /home/robot/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/devel/lib/libhector_gazebo_reset_plugin.so
[  2%] Built target hector_gazebo_reset_plugin
Linking CXX shared library /home/robot/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/devel/lib/libgazebo_ros_force_based_move.so
[  2%] Built target gazebo_ros_force_based_move
Linking CXX shared library /home/robot/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/devel/lib/libdiffdrive_plugin_multi_wheel.so
[  2%] Built target diffdrive_plugin_multi_wheel
make: *** [all] 错误 2
Invoking "make -j4 -l4" failed

**Comment by vmayoral** [comment]
You have dependency issues. I went ahead and reworked the repository to support 16.04 and ROS Kinetic. Either retry with this environment or manually fix the dependency issues.
