### ISSUE TITLE
Failed to install gym-gazebo

### ISSUE THREAD

**Issue by IronLady** [erlerobot/gym-gazebo#44]
I've tried a couple of times to install this and it always failed.
I did in a fresh ubuntu 16.04 installation and use Docker container. 

I ran the docker container and execute "python circuit2_turtlebot_lidar_qlearn.py" and i got "no module named rospy" error.

Is there any correct step-by-step instruction when using Docker container. Because, every time I tried to install this, the error varied from "rospack", "GYM_GAZEBO_WORLD_CIRCUIT' is not set.". It's so confusing

**Comment by vmayoral** [comment]
@IronLady we're not maintaining the docker container anymore. We thought that docker could simplify setting everything up faster and in a simplified way, however as we evolve/change/improve the gym, docker ended up being a pain to maintain. For now, we will keep developing natively. At some point in the future we might (not certain) release another, more mature docker image. 

I'm currently using the gym in 16.04 natively but setting it up, depending on which robot you use might demand some work and understanding of the different components involved.
