### ISSUE TITLE
The example agent pause running strangely!

### ISSUE THREAD

**Issue by larenzhang** [erlerobot/gym-gazebo#49]
There are main two questions when I run the example code.
1.It occured that the program paused strangely almost everytime I run circuit2_turtlebot_lidar_qlearn.py.
And there is no error output.The occasion is as follows:
![screenshot from 2017-11-02 14-25-39](https://user-images.githubusercontent.com/11885069/32312634-c05e8326-bfd9-11e7-9ff9-c6d3dcafc865.png)
2.It seems everything ok and there is no error output when I run circuit2_turtlebot_lidar_dqn.py,but the robot don't move and the program seems to wait something,the output as follows:
![screenshot from 2017-11-02 14-29-51](https://user-images.githubusercontent.com/11885069/32312735-511d2804-bfda-11e7-8cbd-94f7bcfb8bcb.png)

Have you ever encountered these problems?

**Comment by larenzhang** [comment]
I have solved the second question.The reason causing the error is that there are some python2 grammer in circuit2_turtlebot_lidar_dqn.py.I reedit the file to python3 and now it works well.
However,it's hard to converge when I train DQN with just lidar data as inputs.Maybe the hyper-parameters are not quite correct.
Have you train DQN well to solve the enviroment?And could you please offer the worked hyper-parameters?

**Comment by swordsgnat** [comment]
I've been using DQN training, and I get kind of a sine wave of results. The 'bot will get really good after iteration 100 or so, stay good for like 50 iterations, and then tank for the next hundred or two. Then it'll get good again, etc. I've been playing with the epsilon exploration rate decay to see what that did - cutting the exploration rate to zero after the first iteration scoring over, say, 2000, has had a good effect on the quality of the runs afterwards, but the 'bot still fails early about every four iterations or so. I'm still testing / playing with it (and I haven't even started playing with the rewards yet) but I'll let you know if I find anything.

**Comment by vmayoral** [comment]
> @rkojcev @vmayoral @ahcorde @imuguruza @jlamperez
Please do not cite us all. It's a really, really bad practice if you intend to get support from us.

@larenzhang, can you describe your first question in more detail? Can you describe in which system you're currently running the gym? have you tried debugging the environment you're running?

**Comment by Maclapa** [comment]
Hi, I have the same problem as you described. In my case the program pause when it runs for higher number of episodes. The robot in simulation is constantly very slowly moving but I think this is the case of friction of environment.
![screenshot from 2017-12-05 10-33-08](https://user-images.githubusercontent.com/26775551/33600151-b955f698-d9a8-11e7-85b8-ea5b2320478d.png)
![peek 2017-12-05 10-37](https://user-images.githubusercontent.com/26775551/33600162-c50dc7c2-d9a8-11e7-88aa-c64d658bd932.gif)

**Comment by waply** [comment]
@swordsgnat  
Hi, I have the same problem as you described。 the robot gets "stuck" and stops moving forward。
Does anyone have any ideas what this could be or how to fix it?

**Comment by zengjie617789** [comment]
@swordsgnat @larenzhang 
 hi! i have been using the DQN too. but as the same problem "The example agent pause running strangely! "  is there anyone can help to solve these problem?
![image](https://user-images.githubusercontent.com/25050291/39747971-6853097c-52e1-11e8-8e17-187b24f26219.png)

**Comment by pulver22** [comment]
Hi @Maclapa did you understand why the gazebo continuously stopped and the robot moves really slow? I have the same exact behaviour.

**Comment by nzlz** [comment]
This issue is a mix of different issues, @pulver22  please open a new **Bug report** to facilitate issue-tracking. We will be happy to help you.
