### ISSUE TITLE
Multiple Neural Net Outputs

### ISSUE THREAD

**Issue by swordsgnat** [erlerobot/gym-gazebo#62]
Hi! This should be a straightforward question, but it's giving me some difficulty. I'm trying to train a robot with several thrusters, and as such I want the neural network in the DQN version of training to give multiple outputs - one for each thruster value. In the code and in the Keras documentation, it seems like it should be possible, but the `output_size` parameter really seems to change the _magnitude_ of the output, not the dimension.  How would I go about changing the dimension of the output?

Thank you!

**Comment by vmayoral** [comment]
Hello @swordsgnat,

That's a question related to the NN implementation itself to solve the environment and not to any of the environments nor the code here. There's a [keras-users](https://groups.google.com/forum/#!forum/keras-users) forum for that. Post there your code and ask for help. Typically, isolating your code into an "easy-to-reproduce" example makes it easier for people to support you.

2 additional cents, we're not using Keras anymore and are pretty (pretty) happy with Tensorflow. Not sure if the examples in the generic `gym-gazebo` code include any TF network (**contribution opportunity!**) but there're tons of tutorials out there that will get you up and running.

Cheers,
