### ISSUE TITLE
How I expand the observation_space in GazeboCircuit2dTurtlebotLidarEnv

### ISSUE THREAD

**Issue by NanxunDuo** [erlerobot/gym-gazebo#73]
Hi there,
    I am trying to expand the observation_space in GazeboCircuit2dTurtlebotLidarEnv.
    For now the observation in GazeboCircuit2dTurtlebotLidarEnv only includes discretized_ranges, and I wonder if I can add another sensor message in observation.
   I noticed that action_space can be set as spaces.Discrete or Box or other kind of spaces.
   But I read openai gym docs and didn't find any explanation of how to set observation_space.
   Any ideas of setting observation_space?
   Thanks for reading this issue and I will be very appreciate for your valuable suggestion!!

**Comment by zengjie617789** [comment]
had you find a solutions to it?

**Comment by nzlz** [comment]
@NanxunDuo if you are still interested, make sure to open a new **Advice request** issue to facilitate issue-tracking, or post your thought directly at https://github.com/openai/gym/issues.
