### ISSUE TITLE
Ask for help paidly

### ISSUE THREAD

**Issue by gmy2013** [erlerobot/gym-gazebo#78]
Hi, I am interested in reinforcement learning on Ros. But I have met a serious of problems on the process of installing. Could anyone help me with that, I am willing to pay a fee~ Please contact 394138064@qq.com, thanks very much~

**Comment by vmayoral** [comment]
Thanks @gmy2013 for opening up an issue with such disposition. I'm confident someone in the community of the `gym-gazebo` might be willing to support you. 

If nobody reaches out to you after a few days, let me know and I'll try connecting you with someone.

**Comment by gmy2013** [comment]
Thank you very much, I will wait for another 15 days. If there is still nobody, I will contact with you~
