### ISSUE TITLE
Got errors when installing agent dependencies

### ISSUE THREAD

**Issue by swiftwing** [erlerobot/gym-gazebo#89]
I'm running ROS Kinetic on Ubuntu 16.04. I got the following error when run 
`
bash setup_kinetic.bash		
`

![image](https://user-images.githubusercontent.com/16110811/35244955-edf1361c-ff8f-11e7-9484-1662be32eccb.png)
![image](https://user-images.githubusercontent.com/16110811/35244971-03c2e576-ff90-11e7-8f40-280491d112b6.png)

Seems that I'm missing something during compilation.

**Comment by zishanahmed08** [comment]
The errors indicate you missed the instruction below
**pip install rospkg catkin_pkg**

PS- Make sure you use a virtual env or conda env for the python3 ROS environment
