### ISSUE TITLE
Installation (Docker)

### ISSUE THREAD

**Issue by ceobillionaire** [erlerobot/gym-gazebo#9]
On Ubuntu 14.04, when trying to run :

`docker run -it gym-gazebo`

I get : 

> Unable to find image 'gym-gazebo:latest' locally
> Pulling repository docker.io/library/gym-gazebo
> docker: Error: image library/gym-gazebo:latest not found.

PS: The first step (fetching the container) `docker pull erlerobotics/gym-gazebo:latest` was successful (_Status: Image is up to date for erlerobotics/gym-gazebo:latest_).

**Comment by vmayoral** [comment]
Try:
```
docker run -it erlerobotics/gym-gazebo
```

**Comment by ceobillionaire** [comment]
Thanks Víctor 👍
