### ISSUE TITLE
mav_msgs is missing in the gazebo.repos file and ecl* packages are not indigo supported

### ISSUE THREAD

**Issue by ashishk88** [erlerobot/gym-gazebo#97]
These are the correct branches for the ecl* packages:
release/0.61-indigo-kinetic https://github.com/stonier/ecl_core
release/0.61-indigo-kinetic https://github.com/stonier/ecl_lite
release/0.60-indigo-kinetic https://github.com/stonier/ecl_navigation
release/0.61-indigo-kinetic https://github.com/stonier/ecl_tools

**Comment by vmayoral** [comment]
Thanks for reporting.

**Comment by james-yoo** [comment]
It works for me. Thanks!
